/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : Util.java
 * @ Date : 2015/10/13
 * @ Author : 
 *
 */


package com.app2.pms.common;


public class Util {
    public String TAG;
    public void todo() {
    
    }
}
