/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : NetworkManager.java
 * @ Date : 2015/10/13 ÐÇÆÚ¶þ
 * @ Author : 
 *
 */


package com.app2.pms.debug.net;


public class NetworkManager {
    public void connectWebServer() {
    
    }
    
    public void sendData() {
    
    }
    
    public void recvData() {
    
    }
}
