/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : ParseListener.java
 * @ Date : 2015/10/13
 * @ Author : 
 *
 */


package com.app2.pms.debug.data;


public interface ParseListener {
    public void onParseComplete();
}
