/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : ParseModel.java
 * @ Date : 2015/10/13
 * @ Author : 
 *
 */


package com.app2.pms.debug.data;


public class ParseModel {
    private ParseListener mParseListener;
    public void addListener() {
    
    }
    
    public void removeListener() {
    
    }
    
    public void addData() {
    
    }
    
    public void processData() {
    
    }
}
