/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : Session.java
 * @ Date : 2015/10/13 ���ڶ�
 * @ Author : 
 *
 */


package com.app2.pms.debug.exec;


public class Session implements com.app2.pms.debug.exec.ShellListener {
    public ShellExce mShellExce;
    public void startSession() {
    
    }
    
    public void exitSession() {
    
    }
    
    public void onExceComplete() {
    
    }
}
