/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : ShellExce.java
 * @ Date : 2015/10/13 ÐÇÆÚ¶þ
 * @ Author : 
 *
 */


package com.app2.pms.debug.exec;


public class ShellExce {
    private ShellListener mShellListener;
    public void addListener() {
    
    }
    
    public void removeListener() {
    
    }
    
    public void startExce() {
    
    }
}
