/*
 * Generated by StarUML(tm) Java Add-In
 *
 * @ Project : phone manager system
 * @ File Name : MainService.java
 * @ Date : 2015/10/13 ���ڶ�
 * @ Author : 
 *
 */


package com.app2.pms.debug.app;

import android.os.Handler;
import android.os.Message;


public class DebugService implements com.app2.pms.debug.data.ParseListener {
    private ServiceHandler mServiceHandler;
    public com.app2.pms.debug.net.NetworkManager mNetworkManager;
    public com.app2.pms.debug.data.ParseModel mParseModel;
    public com.app2.pms.debug.exec.Session mSession;
    
    private class ServiceHandler extends Handler {
        @Override
        public void handleMessage(Message msg) {
            // TODO Auto-generated method stub
            super.handleMessage(msg);
        }
    
    }
    
    public void sendToHandler() {
    
    }
    
    public void onParseComplete() {
    
    }
}
